plugins:
  digest_append_enable_domain_swap:
    default: false
    client: true
  digest_append_target_domains:
    default: ""
    client: true
    type: list
  digest_append_domain_swap_html_links:
    default: true
    client: true
  digest_append_domain_swap_text_links:
    default: false
    client: true
  digest_append_domain_swap_everywhere:
    default: false
    client: true
  digest_append_domain_swap_headers:
    default: false
    client: true
  digest_append_domain_swap_message_id:
    default: false
    client: true
