# config/settings.yml
plugins:
  digest_append_enable_domain_swap:
    default: false
    client: false

  digest_append_origin_domain:
    default: ""
    client: false

  # MULTIPLE targets: comma / space / newline separated.
  # Example: "track1.myhealthyhaven.org, track2.myhealthyhaven.org track3.myhealthyhaven.org"
  digest_append_target_domains:
    default: ""
    client: false
